### ISSUE TITLE
Thanks for creating this and four proposals.

### ISSUE THREAD

**Issue by zenny** [dobomode/coursera-scraper#2]
@dobomode  It is such a nice to see this happen. Outstanding!

I propose to add the following:

1. Ability of download lecture notes, transcripts of the video in the specified languages and 
2. Ability to download the courses in batch mode with a list of courses
3. Ability to read the login info and CAUTH from a config file (similar to `coursera-dl.conf`)
4. Ability to specify the user's requirements in the config file as above in 3.

Cheers, and stay safe,
/z

**Comment by dobomode** [comment]
Thanks for the suggestions.
At the moment, I don't have any plans to expand the tool with further functionality as this project is intended as a temporary fix while we get the proper fix in `coursera-dl`.
